---
title: "London Gang"
publishDate: "`r Sys.Date()`"
output: 
  blogdown::html_page:
    toc: true
featured: true
editor_options: 
  chunk_output_type: console
image:
  caption: "[The Guardian](https://www.theguardian.com/film/2019/nov/08/rapman-the-london-film-maker-who-gatecrashed-hollywood-in-style#img-3)"
  focal_point: ""
  preview_only: false
tags: 
- street gangs
- crime
- homophily
- heterogeneity
- ethnicity
summary: "Although understood that gangs are commonly ethnically homogenous, it is less common that ethnicity is recognized as having a large impact on the structure and relative activity of gangs.  The article, 'Ethnic heterogeneity in the activity and structure of a Black street gang' by Thomas Grund and James Densley, attempts to move past the broad categorization of Black street gangs to explain the importance of ethnic heterogeneity within the operations and organization of a gang. The data used was reconstructed from anonymized police arrest records for all gang members from 2005 to 2009 as obtained from the relevant Borough Operational Command Unit of London’s Metropolitan Police Service.  Grund and Densley were able to substantiate official records with information provided from sources close to the gang, including the original curators of the data.  Records included information regarding the gang members' country of birth, profilers of the members' illegal activities, and information relating to if two gang members had ever been arrested together for the same offense. Using social network analysis, the authors created a network of the gang members, many of which were also of the same community- allowing for the dynamic nature of gangs, in that gangs are not 'bounded' organizations.  Although the authors were unable to predict future indiscretions as there are no ethnicity related specialization of crime, gang members are more likely to co-offend with members of the same ethnic group."
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

options(warn = 2) # FAIL ON ANY WARNINGS

`%>%` <- magrittr::`%>%`
```

```{r}
proto_net <- COREnets::get_data("london_gang")
# g <- COREnets::core_as_igraph(proto_net)

build_net <- function(edge_table, node_table,
                      edge_class, directed) {
  target_edges <- edge_table[
    edge_table$edge_class == edge_class, 
  ]
  
  target_nodes <- node_table[
    node_table$name %in% c(target_edges$from, target_edges$to), 
  ]
  
  igraph::graph_from_data_frame(
    d = target_edges,
    directed = directed,
    vertices = target_nodes
  )
}

build_nets <- function(proto_net) {
  templates <- split(proto_net$reference$codebook, 
                    seq_len(nrow(proto_net$reference$codebook)))
  names(templates) <- proto_net$reference$codebook$edge_class

  lapply(templates, function(.x) {
    build_net(edge_table = proto_net$network$edges_table, 
              node_table = proto_net$network$nodes_table,
              edge_class = .x$edge_class,
              directed = .x$is_directed)
  })
}

g <- build_nets(proto_net)
```


# Introduction

```{r, results='asis'}
cat(proto_net$reference$description)
```

# Abstract

```{r, results='asis'}
cat(proto_net$reference$abstract)
```

# Code Book


```{r}
knitr::kable(proto_net$reference$codebook)
```


# Sociogram


<!-- ```{r, out.width='100%', fig.height=9} -->
<!-- g %>%  -->
<!--   visNetwork::visIgraph() %>%  -->
<!--   visNetwork::visIgraphLayout(layout = "layout_with_kk", randomSeed = 831) %>%  -->
<!--   visNetwork::visNodes( -->
<!--     color = list(highlight.border = "black"),  -->
<!--     shadow = list(enabled = TRUE, size = 5) -->
<!--   ) %>%  -->
<!--   visNetwork::visOptions( -->
<!--     highlightNearest = list(enabled = TRUE, degree = 1, hover = TRUE), -->
<!--     # selectedBy = list( -->
<!--     #   variable = "group", -->
<!--     #   style = "font-size: 15px" -->
<!--     # ), -->
<!--     nodesIdSelection = list( -->
<!--       enabled = TRUE, -->
<!--       style = "font-size: 15px" -->
<!--     ) -->
<!--   ) %>%  -->
<!--   visNetwork::visInteraction(navigationButtons = TRUE, keyboard = TRUE) %>%  -->
<!--   visNetwork::visExport(name = proto_net$reference$name) -->
<!-- ``` -->


```{r, out.width='100%', fig.height=9}
build_vis_net <- function(g, title) {
  dat <- visNetwork::toVisNetworkData(g)
  
  visNetwork::visNetwork(nodes = dat$nodes, edges = dat$edges,
                         main = title,
                         height = 800,
                         width = 680) %>% 
    visNetwork::visIgraphLayout(layout = "layout_with_kk",
                                randomSeed = 831) %>% 
    visNetwork::visNodes(
      color = list(highlight.border = "black"),
      shadow = list(enabled = TRUE, size = 5)
    ) %>%
    visNetwork::visOptions(
      highlightNearest = list(enabled = TRUE,
                              degree = 1,
                              hover = TRUE),
      nodesIdSelection = list(
        enabled = TRUE,
        style = "font-size: 15px"
      )
    ) %>% 
    visNetwork::visInteraction(navigationButtons = TRUE)
}


# full_g <- igraph::graph_from_data_frame(
#   d = proto_net$network$edges_table,
#   vertices = proto_net$network$nodes_table
# )

# vis_coords <- igraph::layout_with_kk(full_g)

vis_nets <- purrr::imap(g, build_vis_net)

temp_dir <- tempdir(check = TRUE)

for (i in seq_along(vis_nets)) {
 htmlwidgets::saveWidget(
   vis_nets[[i]],
   file = sprintf("%s/London Gang%s.html", temp_dir, i)
  )
}

vis_paths <- dir(temp_dir, pattern = "London Gang\\d+\\.html$",
                 full.names = TRUE)
for_slick <- purrr::map_chr(vis_paths, readr::read_file)

unlink(temp_dir, force = TRUE)

slick <- slickR::slickR(for_slick, slideType = "iframe",
       height = 900, width = "100%") +
  slickR::settings(dots = TRUE, autoplay = FALSE,
                   lazyLoad = "ondemand")

widgetframe::frameWidget(slick, width = "100%")
```



<br><br><br><br>

# Get the Data

## Tables

### Nodes

```{r}
proto_net$network$nodes_table %>% 
  tibble::as_tibble() %>%
  DT::datatable(
    rownames = FALSE,
    filter="top",
    extensions = "Buttons",
    options = list(
      dom = "Bfrtip",
      buttons = list(
        "copy", "print",
        list(extend = "csv", filename = glue::glue("{proto_net$network$nodes_table}_nodes")),
        list(extend = "excel", filename = glue::glue("{proto_net$network$nodes_table}_nodes"))
      ),
      pageLength = 10,
      scrollX = TRUE
    )
  ) %>%
  widgetframe::frameWidget(height = "auto")
```


### Edges


```{r}
proto_net$network$edges_table %>% 
  tibble::as_tibble() %>%
  dplyr::rename(source = from, target = to) %>%
  DT::datatable(
    rownames = FALSE,
    filter="top",
    extensions = "Buttons",
    options = list(
      dom = "Bfrtip",
      buttons = list(
        "copy", "print",
        list(extend = "csv", filename = glue::glue("{proto_net$network$edge_table}_edges")),
        list(extend = "excel", filename = glue::glue("{proto_net$network$edge_table}_edges"))
      ),
      pageLength = 10,
      scrollX = TRUE
    )
  ) %>%
  widgetframe::frameWidget(height = "auto")
```


# Citation


```{r, results='asis'}
proto_net$reference$bibtex
```




