---
title: "Dumbledore's Army"
publishDate: "`r Sys.Date()`"
output: 
  blogdown::html_page:
    toc: true
featured: true
editor_options: 
  chunk_output_type: console
tags: 
- trust
- strong ties
- centrality
- network topography
summary: "Network approaches for analyzing narratives and other texts are being used with increasing frequency. They are seen as capable of identifying key actors and events, highlighting semantic structures, and uncovering underlying meanings and mental models. Numerous network approaches exist. In this paper, the authors adopt an approach where the characters in the story are nodes and the ties linking indicate some type of interaction between them. The authors explore the effects of tie strength between members of two “dark networks” found in the Harry Potter novels—Dumbledore’s Army and Voldemort’s Death Eaters. Drawing on centrality measures, this analysis finds that a handful of secondary characters play roles as important, or almost as important, as Harry Potter and Lord Voldemort. Moreover, a comparison of the topographical structure of the two networks suggests that if the fictional world of Harry Potter remotely mirrors the real one, Dumbledore’s Army is built to withstand stress and uncertainty, while the Death Eaters is not, suggesting that that J. K. Rowling has an intuitive understanding of a key difference between networks built on trust and those built on fear. The former live to fight another day; the latter do not."
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

options(warn = 2) # FAIL ON ANY WARNINGS

`%>%` <- magrittr::`%>%`
```

```{r}
proto_net <- COREnets::get_data("harry_potter_dumbledores_army")
g <- COREnets::core_as_igraph(proto_net)
```


# Introduction

```{r, results='asis'}
cat(proto_net$reference$description)
```

# Abstract

```{r, results='asis'}
cat(proto_net$reference$abstract)
```

# Code Book


```{r}
knitr::kable(proto_net$reference$codebook)
```


# Sociogram


```{r, out.width='100%', fig.height=9}
g %>% 
  visNetwork::visIgraph() %>% 
  visNetwork::visIgraphLayout(layout = "layout_with_kk", randomSeed = 831) %>% 
  visNetwork::visNodes(
    color = list(highlight.border = "black"), 
    shadow = list(enabled = TRUE, size = 5)
  ) %>% 
  visNetwork::visOptions(
    highlightNearest = list(enabled = TRUE, degree = 1, hover = TRUE),
    # selectedBy = list(
    #   variable = "group",
    #   style = "font-size: 15px"
    # ),
    nodesIdSelection = list(
      enabled = TRUE,
      style = "font-size: 15px"
    )
  ) %>% 
  visNetwork::visInteraction(navigationButtons = TRUE, keyboard = TRUE) %>% 
  visNetwork::visExport(name = proto_net$reference$name)
```


# Get the Data

## Tables

### Nodes

```{r}
proto_net$network$nodes_table %>% 
  tibble::as_tibble() %>%
  DT::datatable(
    rownames = FALSE,
    filter="top",
    extensions = "Buttons",
    options = list(
      dom = "Bfrtip",
      buttons = list(
        "copy", "print",
        list(extend = "csv", filename = glue::glue("{proto_net$network$nodes_table}_nodes")),
        list(extend = "excel", filename = glue::glue("{proto_net$network$nodes_table}_nodes"))
      ),
      pageLength = 10,
      scrollX = TRUE
    )
  ) %>%
  widgetframe::frameWidget(height = "auto")
```


### Edges


```{r}
proto_net$network$edges_table %>% 
  tibble::as_tibble() %>%
  dplyr::rename(source = from, target = to) %>%
  DT::datatable(
    rownames = FALSE,
    filter="top",
    extensions = "Buttons",
    options = list(
      dom = "Bfrtip",
      buttons = list(
        "copy", "print",
        list(extend = "csv", filename = glue::glue("{proto_net$network$edge_table}_edges")),
        list(extend = "excel", filename = glue::glue("{proto_net$network$edge_table}_edges"))
      ),
      pageLength = 10,
      scrollX = TRUE
    )
  ) %>%
  widgetframe::frameWidget(height = "auto")
```


# Citation


```{r, results='asis'}
proto_net$reference$bibtex
```




