---
title: "{{{TITLE}}}"
publishDate: "`r Sys.Date()`"
output: 
  blogdown::html_page:
    toc: true
featured: true
editor_options: 
  chunk_output_type: console
tags: "{{{TAGS}}}"
summary: "{{{SUMMARY}}}"
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

options(warn = 2) # FAIL ON ANY WARNINGS

`%>%` <- magrittr::`%>%`
```

```{r}
proto_net <- COREnets::get_data("{{{PROTO_NET_NAME}}}")
g <- COREnets::core_as_igraph(proto_net)
```


# Introduction

```{r, results='asis'}
cat(proto_net$reference$description)
```

# Abstract

```{r, results='asis'}
cat(proto_net$reference$abstract)
```

# Code Book


```{r}
knitr::kable(proto_net$reference$codebook)
```


# Sociogram


```{r, out.width='100%', fig.height=9}
g %>% 
  visNetwork::visIgraph() %>% 
  visNetwork::visIgraphLayout(layout = "layout_with_kk", randomSeed = 831) %>% 
  visNetwork::visNodes(
    color = list(highlight.border = "black"), 
    shadow = list(enabled = TRUE, size = 5)
  ) %>% 
  visNetwork::visOptions(
    highlightNearest = list(enabled = TRUE, degree = 1, hover = TRUE),
    # selectedBy = list(
    #   variable = "group",
    #   style = "font-size: 15px"
    # ),
    nodesIdSelection = list(
      enabled = TRUE,
      style = "font-size: 15px"
    )
  ) %>% 
  visNetwork::visInteraction(navigationButtons = TRUE, keyboard = TRUE) %>% 
  visNetwork::visExport(name = proto_net$reference$name)
```


# Get the Data

## Tables

### Nodes

```{r}
proto_net$network$nodes_table %>% 
  tibble::as_tibble() %>%
  DT::datatable(
    rownames = FALSE,
    filter="top",
    extensions = "Buttons",
    options = list(
      dom = "Bfrtip",
      buttons = list(
        "copy", "print",
        list(extend = "csv", filename = glue::glue("{proto_net$network$nodes_table}_nodes")),
        list(extend = "excel", filename = glue::glue("{proto_net$network$nodes_table}_nodes"))
      ),
      pageLength = 10,
      scrollX = TRUE
    )
  ) %>%
  widgetframe::frameWidget(height = "auto")
```


### Edges


```{r}
proto_net$network$edges_table %>% 
  tibble::as_tibble() %>%
  dplyr::rename(source = from, target = to) %>%
  DT::datatable(
    rownames = FALSE,
    filter="top",
    extensions = "Buttons",
    options = list(
      dom = "Bfrtip",
      buttons = list(
        "copy", "print",
        list(extend = "csv", filename = glue::glue("{proto_net$network$edge_table}_edges")),
        list(extend = "excel", filename = glue::glue("{proto_net$network$edge_table}_edges"))
      ),
      pageLength = 10,
      scrollX = TRUE
    )
  ) %>%
  widgetframe::frameWidget(height = "auto")
```


# Citation


```{r, results='asis'}
proto_net$reference$bibtex
```




