---
title: "The Noordin Top Terrorist Network"
publishDate: "`r Sys.Date()`"
output: 
  blogdown::html_page:
    toc: true
featured: true
editor_options: 
  chunk_output_type: console
image:
  caption: "[Researchgate](https://www.researchgate.net/publication/266465594_Tracking_destabilizing_and_disrupting_dark_networks_with_social_network_analysis_Dark_Networks_Course_Manual/figures?lo=1)"
  focal_point: ""
  preview_only: false
tags: 
- jihad
- religious terrorism
- suicide bombings
summary: "Social network analysis can be used in a variety of ways to combat dark network, as used in 'Strategies for Combating Dark Networks' by Nancy Roberts and Sean Everton, kinetic and non-kinetic approaches can be used to disrupt and counter dark networks such as terrorist operations.  Kinetic approaches involve 'aggressive and offensive measures to eliminate or capture network members, and their supporters,' (Roberts, Everton, 2012), while non-kinetic measures involve 'the use of subtle, non-coercive means for combating dark networks,'. Roberst and Everton use network data from Noordin Top’s South East Asian terror network to demonstrate the effectiveness of both strategies. By using topographical social network analysis metrics, the authors discerned the ability to weaken a dark network through two kinetic strategies: targeting and capacity building, and four non-kinetic approaches: institution-building, psychological operations, information operations, and rehabilitation.  Although distinct approaches, using all six approaches is recommended to create a well-rounded counter-approach to extremism, while also paying attention to the different levels of node analysis- at the individual and organization level.   "
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

options(warn = 2) # FAIL ON ANY WARNINGS

`%>%` <- magrittr::`%>%`
```

```{r}
proto_net <- COREnets::get_data("noordin_139")
# g <- COREnets::core_as_igraph(proto_net)

build_net <- function(edge_table, node_table,
                      edge_class, directed) {
  target_edges <- edge_table[
    edge_table$edge_class == edge_class, 
  ]
  
  target_nodes <- node_table[
    node_table$name %in% c(target_edges$from, target_edges$to), 
  ]
  
  igraph::graph_from_data_frame(
    d = target_edges,
    directed = directed,
    vertices = target_nodes
  )
}

build_nets <- function(proto_net) {
  templates <- split(proto_net$reference$codebook, 
                    seq_len(nrow(proto_net$reference$codebook)))
  names(templates) <- proto_net$reference$codebook$edge_class

  lapply(templates, function(.x) {
    build_net(edge_table = proto_net$network$edges_table, 
              node_table = proto_net$network$nodes_table,
              edge_class = .x$edge_class,
              directed = .x$is_directed)
  })
}

g <- build_nets(proto_net)
```


# Introduction

```{r, results='asis'}
cat(proto_net$reference$description)
```

# Abstract

```{r, results='asis'}
cat(proto_net$reference$abstract)
```

# Code Book


```{r}
knitr::kable(proto_net$reference$codebook)
```


# Sociogram


<!-- ```{r, out.width='100%', fig.height=9} -->
<!-- g %>%  -->
<!--   visNetwork::visIgraph() %>%  -->
<!--   visNetwork::visIgraphLayout(layout = "layout_with_kk", randomSeed = 831) %>%  -->
<!--   visNetwork::visNodes( -->
<!--     color = list(highlight.border = "black"),  -->
<!--     shadow = list(enabled = TRUE, size = 5) -->
<!--   ) %>%  -->
<!--   visNetwork::visOptions( -->
<!--     highlightNearest = list(enabled = TRUE, degree = 1, hover = TRUE), -->
<!--     # selectedBy = list( -->
<!--     #   variable = "group", -->
<!--     #   style = "font-size: 15px" -->
<!--     # ), -->
<!--     nodesIdSelection = list( -->
<!--       enabled = TRUE, -->
<!--       style = "font-size: 15px" -->
<!--     ) -->
<!--   ) %>%  -->
<!--   visNetwork::visInteraction(navigationButtons = TRUE, keyboard = TRUE) %>%  -->
<!--   visNetwork::visExport(name = proto_net$reference$name) -->
<!-- ``` -->


```{r, out.width='100%', fig.height=9}
build_vis_net <- function(g, title) {
  dat <- visNetwork::toVisNetworkData(g)
  
  visNetwork::visNetwork(nodes = dat$nodes, edges = dat$edges,
                         main = title,
                         height = 800,
                         width = 680) %>% 
    visNetwork::visIgraphLayout(layout = "layout_with_kk",
                                randomSeed = 831) %>% 
    visNetwork::visNodes(
      color = list(highlight.border = "black"),
      shadow = list(enabled = TRUE, size = 5)
    ) %>%
    visNetwork::visOptions(
      highlightNearest = list(enabled = TRUE,
                              degree = 1,
                              hover = TRUE),
      nodesIdSelection = list(
        enabled = TRUE,
        style = "font-size: 15px"
      )
    ) %>% 
    visNetwork::visInteraction(navigationButtons = TRUE)
}


# full_g <- igraph::graph_from_data_frame(
#   d = proto_net$network$edges_table,
#   vertices = proto_net$network$nodes_table
# )

# vis_coords <- igraph::layout_with_kk(full_g)

vis_nets <- purrr::imap(g, build_vis_net)

temp_dir <- tempdir(check = TRUE)

for (i in seq_along(vis_nets)) {
 htmlwidgets::saveWidget(
   vis_nets[[i]],
   file = sprintf("%s/The Noordin Top Terrorist Network%s.html", temp_dir, i)
  )
}

vis_paths <- dir(temp_dir, pattern = "The Noordin Top Terrorist Network\\d+\\.html$",
                 full.names = TRUE)
for_slick <- purrr::map_chr(vis_paths, readr::read_file)

unlink(temp_dir, force = TRUE)

slick <- slickR::slickR(for_slick, slideType = "iframe",
       height = 900, width = "100%") +
  slickR::settings(dots = TRUE, autoplay = FALSE,
                   lazyLoad = "ondemand")

widgetframe::frameWidget(slick, width = "100%")
```



<br><br><br><br>

# Get the Data

## Tables

### Nodes

```{r}
proto_net$network$nodes_table %>% 
  tibble::as_tibble() %>%
  DT::datatable(
    rownames = FALSE,
    filter="top",
    extensions = "Buttons",
    options = list(
      dom = "Bfrtip",
      buttons = list(
        "copy", "print",
        list(extend = "csv", filename = glue::glue("{proto_net$network$nodes_table}_nodes")),
        list(extend = "excel", filename = glue::glue("{proto_net$network$nodes_table}_nodes"))
      ),
      pageLength = 10,
      scrollX = TRUE
    )
  ) %>%
  widgetframe::frameWidget(height = "auto")
```


### Edges


```{r}
proto_net$network$edges_table %>% 
  tibble::as_tibble() %>%
  dplyr::rename(source = from, target = to) %>%
  DT::datatable(
    rownames = FALSE,
    filter="top",
    extensions = "Buttons",
    options = list(
      dom = "Bfrtip",
      buttons = list(
        "copy", "print",
        list(extend = "csv", filename = glue::glue("{proto_net$network$edge_table}_edges")),
        list(extend = "excel", filename = glue::glue("{proto_net$network$edge_table}_edges"))
      ),
      pageLength = 10,
      scrollX = TRUE
    )
  ) %>%
  widgetframe::frameWidget(height = "auto")
```


# Citation


```{r, results='asis'}
proto_net$reference$bibtex
```




